# Generated by Django 5.2.5 on 2025-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_streak_swotitem_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swotitem',
            options={},
        ),
        migrations.AddField(
            model_name='swotitem',
            name='dow_mask',
            field=models.SmallIntegerField(default=127),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='month_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
